/*
 * Name: QuizResults.java
 * Date: June 8th, 2015
 * Version: v0.1
 * Author: Ryan Protheroe
 * Description: Displays score and end message based off score from quiz
 */
package edu.hdsb.gwss.protheroe.ics3u.performanceTask;

/**
 *
 * @author muirwa
 */
public class QuizResults extends javax.swing.JFrame {

    /**
     * Creates new form QuizResults
     */
    public QuizResults(int score) {
        initComponents();
        scoreDisplay.setText("" + score + "/" + 10);

        //Displays message based off score
        if (score == 10) {
            endMessage.setText("BOI YOU STYLIN!!!!");
        } else if (score > 8) {
            endMessage.setText("Nice");
        } else if (score > 5) {
            endMessage.setText("Meh, you could’ve done better");
        } else if (score > 2) {
            endMessage.setText("Study harder next time");
        } else if (score >= 0) {
            endMessage.setText("ARE YOU EVEN IN THIS CLASS?!?!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        resultsHeader = new javax.swing.JLabel();
        scoreDisplay = new javax.swing.JLabel();
        endMessage = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        endBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 450));
        getContentPane().setLayout(null);

        resultsHeader.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        resultsHeader.setForeground(new java.awt.Color(255, 255, 255));
        resultsHeader.setText("How well did you do?");
        getContentPane().add(resultsHeader);
        resultsHeader.setBounds(96, 31, 308, 47);

        scoreDisplay.setFont(new java.awt.Font("Haettenschweiler", 0, 60)); // NOI18N
        scoreDisplay.setForeground(new java.awt.Color(255, 255, 255));
        scoreDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreDisplay.setText("Score");
        getContentPane().add(scoreDisplay);
        scoreDisplay.setBounds(124, 96, 245, 186);

        endMessage.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        endMessage.setForeground(new java.awt.Color(255, 255, 255));
        endMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        endMessage.setText("Message");
        getContentPane().add(endMessage);
        endMessage.setBounds(11, 288, 480, 55);

        exitButton.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        exitButton.setText("Leave");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveQuiz(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(183, 349, 122, 35);

        endBackground.setForeground(new java.awt.Color(255, 255, 255));
        endBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hdsb/gwss/protheroe/ics3u/performanceTask/QuizShowStart.jpg"))); // NOI18N
        getContentPane().add(endBackground);
        endBackground.setBounds(0, 0, 500, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leaveQuiz(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveQuiz
        System.exit(0);
    }//GEN-LAST:event_leaveQuiz

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizResults(2).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel endBackground;
    private javax.swing.JLabel endMessage;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel resultsHeader;
    private javax.swing.JLabel scoreDisplay;
    // End of variables declaration//GEN-END:variables
}
