/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hdsb.gwss.protheroe.ics3u.u6;

/**
 *
 * @author 1protheroery
 */
public class GolfJFrame extends javax.swing.JFrame {

    /**
     * Creates new form GolfJFrame
     */
    public GolfJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterScoreText = new javax.swing.JTextField();
        javax.swing.JTextField amountOfHolesText = new javax.swing.JTextField();
        setAmountOfHolesText = new javax.swing.JTextField();
        holeNumberScoreText = new javax.swing.JTextField();
        tableDisplay = new javax.swing.JTextField();
        otherStats = new javax.swing.JTextField();
        enterButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        enterScoreText.setFont(new java.awt.Font("UPBOLTERS", 0, 36)); // NOI18N
        getContentPane().add(enterScoreText);
        enterScoreText.setBounds(220, 190, 330, 80);

        amountOfHolesText.setFont(new java.awt.Font("UPBOLTERS", 0, 12)); // NOI18N
        getContentPane().add(amountOfHolesText);
        amountOfHolesText.setBounds(90, 220, 60, 40);

        setAmountOfHolesText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        setAmountOfHolesText.setText("Amount of Holes");
        setAmountOfHolesText.setToolTipText("");
        getContentPane().add(setAmountOfHolesText);
        setAmountOfHolesText.setBounds(70, 190, 100, 20);

        holeNumberScoreText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        holeNumberScoreText.setText("Please enter the amount of holes first");
        holeNumberScoreText.setToolTipText("");
        getContentPane().add(holeNumberScoreText);
        holeNumberScoreText.setBounds(280, 160, 200, 20);
        getContentPane().add(tableDisplay);
        tableDisplay.setBounds(30, 300, 520, 370);
        getContentPane().add(otherStats);
        otherStats.setBounds(560, 300, 210, 370);

        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(enterButton);
        enterButton.setBounds(560, 210, 210, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hdsb/gwss/protheroe/ics3u/u6/Golf score.jpg"))); // NOI18N
        background.setToolTipText("");
        getContentPane().add(background);
        background.setBounds(0, 0, 800, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GolfJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GolfJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GolfJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GolfJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GolfJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton enterButton;
    private javax.swing.JTextField enterScoreText;
    private javax.swing.JTextField holeNumberScoreText;
    private javax.swing.JTextField otherStats;
    private javax.swing.JTextField setAmountOfHolesText;
    private javax.swing.JTextField tableDisplay;
    // End of variables declaration//GEN-END:variables
}
