/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hdsb.gwss.protheroe.ics3u.u6;

/**
 *
 * @author 1protheroery
 */
public class GolfJFrame extends javax.swing.JFrame {

    /**
     * Creates new form GolfJFrame
     */
    public GolfJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountOfHolesText = new javax.swing.JTextField();
        holeNumberScoreText = new javax.swing.JTextField();
        tableDisplay = new javax.swing.JTextField();
        lowestScoreText = new javax.swing.JTextField();
        enterButton = new javax.swing.JButton();
        totalScoreText = new javax.swing.JTextField();
        highestScoreText = new javax.swing.JTextField();
        enterScore = new javax.swing.JTextField();
        enterAmountOfHoles = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        amountOfHolesText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amountOfHolesText.setText("Amount of Holes");
        amountOfHolesText.setToolTipText("");
        getContentPane().add(amountOfHolesText);
        amountOfHolesText.setBounds(60, 180, 130, 30);

        holeNumberScoreText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        holeNumberScoreText.setText("Please enter the amount of holes first");
        holeNumberScoreText.setToolTipText("");
        getContentPane().add(holeNumberScoreText);
        holeNumberScoreText.setBounds(270, 150, 230, 30);
        getContentPane().add(tableDisplay);
        tableDisplay.setBounds(30, 300, 520, 370);
        getContentPane().add(lowestScoreText);
        lowestScoreText.setBounds(560, 300, 210, 70);

        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(enterButton);
        enterButton.setBounds(560, 210, 210, 40);
        getContentPane().add(totalScoreText);
        totalScoreText.setBounds(560, 600, 210, 70);
        getContentPane().add(highestScoreText);
        highestScoreText.setBounds(560, 450, 210, 70);

        enterScore.setFont(new java.awt.Font("UPBOLTERS", 0, 48)); // NOI18N
        enterScore.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enterScore.setText("0");
        enterScore.setToolTipText("");
        getContentPane().add(enterScore);
        enterScore.setBounds(220, 190, 330, 80);

        enterAmountOfHoles.setFont(new java.awt.Font("UPBOLTERS", 0, 36)); // NOI18N
        enterAmountOfHoles.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enterAmountOfHoles.setText("0");
        enterAmountOfHoles.setToolTipText("");
        getContentPane().add(enterAmountOfHoles);
        enterAmountOfHoles.setBounds(90, 220, 60, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        amountOfHoles = Integer.parseInt(enterAmountOfHoles.getText());

        if (amountOfHoles > 0) {

            int[] golfScore = new int[amountOfHoles];

            //ACQUIRES SCORES AND ADDS SCORE
            for (int counter = 1; amountOfHoles >= counter; counter++) {

                //USER INPUT
                holeNumberScoreText.setText("Please enter the score of hole #" + counter);
                golfScore[counter - 1] = Integer.parseInt(enterScore.getText());
                total = total + golfScore[counter - 1];

            }
        }
    }//GEN-LAST:event_enterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GolfJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GolfJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GolfJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GolfJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GolfJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountOfHolesText;
    private javax.swing.JTextField enterAmountOfHoles;
    private javax.swing.JButton enterButton;
    private javax.swing.JTextField enterScore;
    private javax.swing.JTextField highestScoreText;
    private javax.swing.JTextField holeNumberScoreText;
    private javax.swing.JTextField lowestScoreText;
    private javax.swing.JTextField tableDisplay;
    private javax.swing.JTextField totalScoreText;
    // End of variables declaration//GEN-END:variables
int amountOfHoles = 0;
int total = 0;
}
