/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hdsb.gwss.protheroe.ics3u.u6;

import java.text.NumberFormat;

/**
 *
 * @author Ryan
 */
public class TemperatureJFrame extends javax.swing.JFrame {

    /**
     * Creates new form TemperatureJFrame
     */
    public TemperatureJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        friday = new javax.swing.JLabel();
        tuesday = new javax.swing.JLabel();
        wednesday = new javax.swing.JLabel();
        sunday = new javax.swing.JLabel();
        thursday = new javax.swing.JLabel();
        saturday = new javax.swing.JLabel();
        javax.swing.JLabel temperatureHeader = new javax.swing.JLabel();
        dayHeader = new javax.swing.JLabel();
        monday = new javax.swing.JLabel();
        enterTemp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        friday.setFont(new java.awt.Font("UPBOLTERS", 0, 48)); // NOI18N
        friday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        friday.setText("?");
        getContentPane().add(friday);
        friday.setBounds(220, 510, 100, 100);

        tuesday.setFont(new java.awt.Font("UPBOLTERS", 0, 48)); // NOI18N
        tuesday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tuesday.setText("?");
        tuesday.setToolTipText("");
        getContentPane().add(tuesday);
        tuesday.setBounds(330, 240, 100, 100);

        wednesday.setFont(new java.awt.Font("UPBOLTERS", 0, 48)); // NOI18N
        wednesday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wednesday.setText("?");
        getContentPane().add(wednesday);
        wednesday.setBounds(530, 240, 100, 100);

        sunday.setFont(new java.awt.Font("UPBOLTERS", 0, 48)); // NOI18N
        sunday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sunday.setText("?");
        sunday.setToolTipText("");
        getContentPane().add(sunday);
        sunday.setBounds(570, 510, 100, 100);

        thursday.setFont(new java.awt.Font("UPBOLTERS", 0, 48)); // NOI18N
        thursday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thursday.setText("?");
        getContentPane().add(thursday);
        thursday.setBounds(50, 510, 100, 100);

        saturday.setFont(new java.awt.Font("UPBOLTERS", 0, 48)); // NOI18N
        saturday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saturday.setText("?");
        saturday.setToolTipText("");
        getContentPane().add(saturday);
        saturday.setBounds(390, 510, 100, 100);

        temperatureHeader.setFont(new java.awt.Font("UPBOLTERS", 0, 18)); // NOI18N
        temperatureHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        temperatureHeader.setText("Temperature");
        temperatureHeader.setToolTipText("");
        temperatureHeader.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(temperatureHeader);
        temperatureHeader.setBounds(10, 180, 120, 20);

        dayHeader.setFont(new java.awt.Font("UPBOLTERS", 0, 18)); // NOI18N
        dayHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayHeader.setText("Monday's");
        dayHeader.setToolTipText("");
        dayHeader.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(dayHeader);
        dayHeader.setBounds(10, 160, 120, 20);

        monday.setFont(new java.awt.Font("UPBOLTERS", 0, 48)); // NOI18N
        monday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monday.setText("?");
        monday.setToolTipText("");
        getContentPane().add(monday);
        monday.setBounds(160, 240, 100, 100);

        enterTemp.setFont(new java.awt.Font("UPBOLTERS", 0, 36)); // NOI18N
        enterTemp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enterTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterTempActionPerformed(evt);
            }
        });
        getContentPane().add(enterTemp);
        enterTemp.setBounds(20, 240, 100, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hdsb/gwss/protheroe/ics3u/u6/Weekly Weather.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterTempActionPerformed
        String[] days = {"Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"};

        int[] temperatures = new int[7];

        //DECIMAL FORMAT
        NumberFormat decimal = NumberFormat.getNumberInstance();
        decimal.setMinimumFractionDigits(1);
        decimal.setMaximumFractionDigits(1);

        //ACQUIRES TEMPERATURES
        for (; 7 >= counter + 1; counter++) {

            //CHANGES HEADER
            dayHeader.setText(days[counter] + "'s");
            temperatures[counter] = Integer.parseInt(enterTemp.getText());
            enterTemp.setText("");
            total = total + temperatures[counter];

            //DECIDES WHAT VALUE TO CHANGE
            switch (counter) {
                case 0:
                    monday.setText(Integer.toString(temperatures[counter]));
                    break;
                case 1:
                    tuesday.setText(Integer.toString(temperatures[counter]));
                    break;
                case 2:
                    wednesday.setText(Integer.toString(temperatures[counter]));
                    break;
                case 3:
                    thursday.setText(Integer.toString(temperatures[counter]));
                    break;
                case 4:
                    friday.setText(Integer.toString(temperatures[counter]));
                    break;
                case 5:
                    saturday.setText(Integer.toString(temperatures[counter]));
                    break;
                case 6:
                    sunday.setText(Integer.toString(temperatures[counter]));
                    break;

            }
        }

        //CALCULATES AVERAGE
        if (counter == 7) {
            double average;
            average = total / 7;
            dayHeader.setText("Average");
            enterTemp.setText(decimal.format(average));
            enterTemp.setEnabled(false);
        }


    }//GEN-LAST:event_enterTempActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemperatureJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemperatureJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemperatureJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemperatureJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemperatureJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dayHeader;
    private javax.swing.JTextField enterTemp;
    private javax.swing.JLabel friday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel monday;
    private javax.swing.JLabel saturday;
    private javax.swing.JLabel sunday;
    private javax.swing.JLabel thursday;
    private javax.swing.JLabel tuesday;
    private javax.swing.JLabel wednesday;
    // End of variables declaration//GEN-END:variables
int total = 0;
    int counter = 0;
}
