/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hdsb.gwss.protheroe.ics3u.u7;

import java.io.File;
import javax.swing.DefaultComboBoxModel;
import nu.xom.Builder;
import nu.xom.Document;
import nu.xom.Element;
import nu.xom.Elements;

/**
 *
 * @author 1protheroery
 */
public class Friends extends javax.swing.JFrame {

    /**
     * Creates new form Friends
     */
    public Friends() {
        initComponents();

        File file = new File("friends.xml");

        Builder builder = new Builder();
        Document friendsDocument;
        Element friendsRoot;

        try {
            //Builder parses file and creates doc
            friendsDocument = builder.build(file);
            friendsRoot = friendsDocument.getRootElement();

            Elements friends = friendsRoot.getChildElements();

            // data goes in the combo box model
            DefaultComboBoxModel model = new DefaultComboBoxModel();

            for (int friend = 0; friend < friends.size(); friend++) {
                model.addElement(friends.get(friend).getFirstChildElement("name").getValue());
            }

            // add model to the combo box
            dropDownMenu.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainHeader = new javax.swing.JLabel();
        nameHeader = new javax.swing.JLabel();
        phoneNumberHeader = new javax.swing.JLabel();
        addressHeader = new javax.swing.JLabel();
        emailHeader = new javax.swing.JLabel();
        dropDownMenu = new javax.swing.JComboBox();
        addressTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        numberTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainHeader.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        mainHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainHeader.setText("Friends Database");

        nameHeader.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        nameHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameHeader.setText("Name");

        phoneNumberHeader.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        phoneNumberHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phoneNumberHeader.setText("Phone Number");

        addressHeader.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        addressHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addressHeader.setText("Address");

        emailHeader.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        emailHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailHeader.setText("Email");

        dropDownMenu.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        dropDownMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dropDownMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDownMenuActionPerformed(evt);
            }
        });

        addressTextField.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        addressTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addressTextField.setToolTipText("");

        emailTextField.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        emailTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailTextField.setToolTipText("");

        numberTextField.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        numberTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numberTextField.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailHeader)
                            .addComponent(addressHeader)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(113, 113, 113)
                                    .addComponent(nameHeader))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(phoneNumberHeader))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dropDownMenu, 0, 215, Short.MAX_VALUE)
                            .addComponent(addressTextField)
                            .addComponent(emailTextField)
                            .addComponent(numberTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(183, 183, 183))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(mainHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropDownMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addressTextField)
                    .addComponent(addressHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phoneNumberHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberTextField))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailTextField)
                    .addComponent(emailHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropDownMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDownMenuActionPerformed

        // the selected item in the combo box
        int index = dropDownMenu.getSelectedIndex();

        // the value (text) of the item in the combo box
        String value = (String) dropDownMenu.getSelectedItem();

        addressTextField = friends.get(index).getFirstChildElement("address").getValue();
        numberTextField = friends.get(index).getFirstChildElement("address").getValue();
        emailTextField = friends.get(index).getFirstChildElement("address").getValue();

    }//GEN-LAST:event_dropDownMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Friends().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressHeader;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JComboBox dropDownMenu;
    private javax.swing.JLabel emailHeader;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel mainHeader;
    private javax.swing.JLabel nameHeader;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JLabel phoneNumberHeader;
    // End of variables declaration//GEN-END:variables
}
